apiVersion: apps/v1
kind: Deployment
metadata:
  name: ontological-concepts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ontological-concepts
  template:
    metadata:
      labels:
        app: ontological-concepts
    spec:
      containers:
      - name: ontological-concepts
        image: your-container-registry/ontological-concepts:latest
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: ontological-concepts
spec:
  selector:
    app: ontological-concepts
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
